### ISSUE TITLE
Welcome Page

### ISSUE THREAD

**Issue by thewillsmith** [dominicegginton/hue#9]
Updating the Welcome Page to be more appealing to the eyes, meaning a smaller Start button or a complete redesign, will be discussed later on in the development process

**Comment by dominicegginton** [comment]
Can someone post some design ideas ?

**Comment by Smifeh** [comment]
onto where? Which bit? Waffle?

________________________________

**Comment by dominicegginton** [comment]
@Smifeh  on github
